{{- if .Values.ingress.enabled -}}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "ipam.fullname" . }}-ingress-route
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "ipam.labels" . | nindent 4 }}
spec:
  entryPoints:
    - web
    - websecure
  routes:
    # Backend Route (API)
    - match: Host(`{{ .Values.ingress.host }}`) && PathPrefix(`/api`)
      kind: Rule
      services:
        - name: {{ include "ipam.fullname" . }}-backend
          port: {{ .Values.backend.service.port }}

    # Frontend Route (SPA)
    - match: Host(`{{ .Values.ingress.host }}`)
      kind: Rule
      services:
        - name: {{ include "ipam.fullname" . }}-frontend
          port: {{ .Values.frontend.service.port }}
{{- end }}
