{{- if .Values.postgres.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ipam.fullname" . }}-postgres
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "ipam.labels" . | nindent 4 }}
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "ipam.selectorLabels" . | nindent 6 }}
      app: postgres
  template:
    metadata:
      labels:
        {{- include "ipam.selectorLabels" . | nindent 8 }}
        app: postgres
    spec:
      containers:
        - name: postgres
          image: "{{ .Values.postgres.image.repository }}:{{ .Values.postgres.image.tag }}"
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "ipam.fullname" . }}-backend-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "ipam.fullname" . }}-backend-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              value: {{ .Values.postgres.auth.database }}
          {{- if .Values.postgres.persistence.enabled }}
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
          {{- end }}
      {{- if .Values.postgres.persistence.enabled }}
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: {{ include "ipam.fullname" . }}-postgres-pvc
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ipam.fullname" . }}-postgres
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "ipam.labels" . | nindent 4 }}
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    {{- include "ipam.selectorLabels" . | nindent 4 }}
    app: postgres
---
{{- if .Values.postgres.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "ipam.fullname" . }}-postgres-pvc
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "ipam.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- toYaml .Values.postgres.persistence.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.postgres.persistence.size }}
{{- end }}
{{- end }}
