apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ipam.fullname" . }}-backend-secret
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "ipam.labels" . | nindent 4 }}
type: Opaque
stringData:
  SECRET_KEY: {{ .Values.backend.secret.secretKey | quote }}
  JWT_SECRET_KEY: {{ .Values.backend.secret.jwtSecretKey | quote }}
  POSTGRES_USER: {{ .Values.postgres.auth.username | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.auth.password | quote }}
  DATABASE_URI: "postgresql://{{ .Values.postgres.auth.username }}:{{ .Values.postgres.auth.password }}@{{ include "ipam.fullname" . }}-postgres:5432/{{ .Values.postgres.auth.database }}"
